name: Pithos
description: Pithos is a large container used by the ancient Greeks for bulk storage, primarily for fluids and grains. They're comparable to the drums, barrels, and casks of recent times.
markdown: kramdown
baseurl: /pithos
twitter_username: anindita_basu
github_username: AninditaBasu
author: ab.techwriter@gmail.com
#
theme: minima
#
# remote theme
#remote_theme: just-the-docs/just-the-docs
#logo: "/images/ideogram.png"
#search_enabled: true
#search:
#  heading_level: 2
#  previews: 3
#footer_content: "Copyright &copy; 2022 Anindita Basu"
#back_to_top: true
#back_to_top_text: "Back to top"